#!/bin/bash
set -eux

sudo chsh -s /bin/zsh "$(whoami)"

formulas=( \
  wget \
  curl \
  git \
  zsh \
  vim \
  htop \
  redis \
  go \
  haskell-stack \
  mackerelio/mackerel-agent/mackerel-agent \
  mackerelio/mackerel-agent/mkr \
)

for formula in "${formulas[@]}"; do
  tools/brew-install "$formula"
done
