#!/bin/bash
set -euxo pipefail

formulas=( \
  docker \
  iterm2 \
  google-japanese-ime \
  google-chrome \
  firefox \
  slack \
  hammerspoon \
  dropbox \
)

for formula in "${formulas[@]}"; do
  tools/brew-cask-install "$formula"
done

# iTerm2
defaults write com.googlecode.iterm2 NSUserKeyEquivalents -dict-add 'Quit iTerm2' '@~^q'

# Google Chrome
defaults write com.google.Chrome NSUserKeyEquivalents -dict-add 'Quit Google Chrome' '@~^q'

# Hammerspoon
defaults write com.hammerspoon.Hammerspoon HSUploadCrashData -bool false
defaults write com.hammerspoon.Hammerspoon MJShowDockIconKey -bool false
defaults write org.hammerspoon.Hammerspoon MJConfigFile "$XDG_CONFIG_HOME/hammerspoon/init.lua"
tools/make-symlink "$XDG_CONFIG_HOME/dotfiles/.init.lua" "$XDG_CONFIG_HOME/hammerspoon/init.lua"
osascript -e 'tell application "Hammerspoon" to quit'
