#!/bin/bash
set -eu

if command -v brew >/dev/null; then
  exit
fi

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

eval "$(/opt/homebrew/bin/brew shellenv)"

if ! grep -q "brew shellenv" ~/.zprofile; then
  printf "eval \"\$(/opt/homebrew/bin/brew shellenv)\"" >>~/.zprofile
fi
