#!/bin/bash
set -euxo pipefail

formulas=(
  docker
  iterm2
  google-chrome
  firefox
  slack
  hammerspoon
  dropbox
  font-inconsolata
)

for formula in "${formulas[@]}"; do
  tools/brew-cask-install "$formula"
done

# iTerm2
defaults write com.googlecode.iterm2 NSUserKeyEquivalents -dict-add 'Quit iTerm2' '@~^q'
defaults write com.googlecode.iterm2 NSUserKeyEquivalents -dict-add 'Close' '@^w'
defaults write com.googlecode.iterm2 NSUserKeyEquivalents -dict-add 'New Window' '@^n'

# Hammerspoon
defaults write com.hammerspoon.Hammerspoon HSUploadCrashData -bool false
defaults write com.hammerspoon.Hammerspoon MJShowDockIconKey -bool false
defaults write org.hammerspoon.Hammerspoon MJConfigFile "$XDG_CONFIG_HOME/hammerspoon/init.lua"
tools/make-symlink "$XDG_CONFIG_HOME/dotfiles/.init.lua" "$XDG_CONFIG_HOME/hammerspoon/init.lua"
if pgrep -q -f Hammerspoon.app; then
  osascript -e 'tell application "Hammerspoon" to quit'
  open -a Hammerspoon
fi

# Font
fc-cache -vf
