#!/bin/bash
set -euxo pipefail

formulas=( \
  wget \
  curl \
  git \
  hub \
  jq \
  zsh \
  vim \
  tmux \
  htop \
  redis \
  go \
  ruby \
  haskell-stack \
  rust \
  shellcheck \
  envchain \
  \
  mackerelio/mackerel-agent/mackerel-agent \
  mackerelio/mackerel-agent/mkr \
  \
  itchyny/tap/git-branch-name \
  itchyny/tap/fillin \
  itchyny/tap/miv \
  itchyny/tap/qhs \
  itchyny/tap/rexdep \
  itchyny/tap/gojo \
  itchyny/tap/gojq \
  itchyny/tap/mkrg \
  itchyny/tap/formulate \
  \
  Songmu/tap/blogsync \
)

for formula in "${formulas[@]}"; do
  tools/brew-install "$formula"
done

if command -v miv >/dev/null 2>&1; then
  miv install
  cd "$(miv path vimproc)" && make
fi
