#!/bin/bash
set -euxo pipefail

formulas=( \
  java \
  iterm2 \
  google-japanese-ime \
  google-chrome \
  firefox \
  slack \
  hammerspoon \
  flux \
)

for formula in "${formulas[@]}"; do
  tools/brew-cask-install "$formula"
done

tools/make-symlink ~/{.files,.hammerspoon}/init.lua
