#!/bin/bash
set -euxo pipefail

target=$XDG_CONFIG_HOME/dotfiles

tools/git-clone https://github.com/itchyny/dotfiles "$target"

tools/make-symlink "$target/.zshrc" ~/.zshrc
tools/make-symlink "$target/.vimrc" "$XDG_CONFIG_HOME/vim/vimrc"
tools/make-symlink "$target/.vimrc.yaml" "$XDG_CONFIG_HOME/miv/config.yaml"
tools/make-symlink "$target/.tmux.conf" "$XDG_CONFIG_HOME/tmux/tmux.conf"
tools/make-symlink "$target/.irbrc" "$XDG_CONFIG_HOME/irb/irbrc"

mkdir -p "$XDG_DATA_HOME"/{vim/{swap,backup,undo,tmp},miv,zsh}

export ZINIT_HOME="$XDG_DATA_HOME"/zinit
sh -c "$(curl -fsSL https://raw.githubusercontent.com/zdharma-continuum/zinit/HEAD/scripts/install.sh)"
touch ~/.zprofile
