#!/bin/bash
set -euxo pipefail

target=~/.files

tools/git-clone https://github.com/itchyny/dotfiles "$target"

for f in .vimrc .vimrc.yaml .zshrc .tmux.conf; do
  tools/make-symlink "$target/$f" ~/"$f"
done
