#!/bin/bash
set -eux

if ! command -v defaults >/dev/null; then
  echo "finder: defaults not found" > /dev/stderr
  exit
fi

if ! command -v osascript >/dev/null; then
  echo "finder: osascript not found" > /dev/stderr
  exit
fi

defaults write com.apple.finder QuitMenuItem -bool YES
osascript -e 'tell application "Finder" to quit'
