#!/bin/bash
set -eux

cmdname="$(basename "${BASH_SOURCE[0]}")"

if ! command -v stack >/dev/null; then
  echo "$cmdname: stack not found" > /dev/stderr
  exit
fi

if command -v miv >/dev/null; then
  exit
fi

target=~/Documents/itchyny/miv

if [ -e "$target" ]; then
  echo "$target exists" > /dev/stderr
  exit
fi

tools/git-clone https://github.com/itchyny/miv "$target"

cd "$target"
stack install
miv=~/.local/bin/miv
$miv install
cd "$($miv path vimproc)" && make
