#!/bin/bash
set -eux

if ! command -v defaults >/dev/null; then
  echo "trackpad: defaults not found" > /dev/stderr
  exit
fi

# Trackpad: enable tap to click for this user and for the login screen
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking -bool true
defaults -currentHost write NSGlobalDomain com.apple.mouse.tapBehavior -int 1
defaults write NSGlobalDomain com.apple.mouse.tapBehavior -int 1
