#!/bin/bash
set -euxo pipefail

target=$XDG_DATA_HOME/zsh

if ! [ -e "$target" ]; then
  mkdir -p "$target"
fi

# http://mimosa-pudica.net/zsh-incremental.html
if ! [ -e "$target/incr-0.2.zsh" ]; then
  curl -L http://mimosa-pudica.net/src/incr-0.2.zsh \
    | sed 's/^\(bindkey.*backward-delete-char-incr\)/# \1/' \
    > "$target/incr-0.2.zsh"
fi

plugins=( \
  itchyny/zsh-auto-fillin \
  itchyny/zsh-git-alias \
  zsh-users/zsh-syntax-highlighting \
  zsh-users/zsh-history-substring-search \
)

for name in "${plugins[@]}"; do
  if ! [ -e "$target/${name##*/}" ]; then
    git clone "https://github.com/$name" "$target/${name##*/}"
  fi
done

find "$target" -name '*.zsh' -type f -exec zsh -c 'test -f {}.zwc || zcompile {}' \;
