#!/bin/bash
set -euxo pipefail

cmdname="$(basename "${BASH_SOURCE[0]}")"

cd "$(dirname "$0")/.."

if ! command -v shellcheck >/dev/null; then
  echo "$cmdname: shellcheck is required" >&2
  exit 1
fi

git ls-files -s | grep ^100755 | cut -f2 | xargs shellcheck
