#!/bin/bash
set -euxo pipefail

readonly CMDNAME="${BASH_SOURCE[0]##*/}"

if ! command -v shellcheck >/dev/null; then
  echo "$CMDNAME: shellcheck is required" >&2
  exit 1
fi

cd "$(dirname "${BASH_SOURCE[0]}")/.."
git ls-files -s | grep ^100755 | cut -f2 | xargs shellcheck
