#!/bin/bash
set -euxo pipefail

cmdname="$(basename "${BASH_SOURCE[0]}")"

cd "$(dirname "$0")/.."

if ! command -v shellcheck >/dev/null; then
  echo "$cmdname: shellcheck is required" > /dev/stderr
  exit 1
fi

files=$(git ls-files -s | grep 755 | awk '{ print $4 }')

for f in $files; do
  shellcheck -x "$f"
done
