#!/bin/bash
set -euo pipefail

cmdname="$(basename "${BASH_SOURCE[0]}")"

if [[ $# -ne 1 ]]; then
  echo "Usage: $cmdname formula" >&2
  exit 1
fi

formula=$1

if ! brew list --cask --versions "$formula"; then
  brew install --cask "$formula"
fi
