#!/bin/bash

cmdname="$(basename "${BASH_SOURCE[0]}")"

if [[ $# -ne 1 ]]; then
  echo "Usage: $cmdname formula" >&2
  exit 1
fi

formula=$1

if ! brew ls --versions "$formula"; then
  brew install "$formula"
fi
