#!/bin/bash
set -euo pipefail

readonly CMDNAME="${BASH_SOURCE[0]##*/}"

if [[ $# -ne 1 ]]; then
  echo "Usage: $CMDNAME formula" >&2
  exit 1
fi

formula=$1

if ! brew list --versions "$formula"; then
  brew install "$formula"
fi
