#!/bin/bash
set -euo pipefail

readonly CMDNAME="${BASH_SOURCE[0]##*/}"

if [[ $# -ne 2 ]]; then
  echo "Usage: $CMDNAME repo target" >&2
  exit 1
fi

repo=$1
target=$2

if [[ -e "$target" ]]; then
  echo "Target $target exists. Skipping cloning $repo." >&2
else
  git clone "$repo" "$target"
fi
