#!/bin/bash

cmdname="$(basename "${BASH_SOURCE[0]}")"

if [[ $# -lt 1 ]] || [[ $# -gt 2 ]]; then
  echo "Usage: $cmdname repo target" >&2
  exit 1
fi

repo=$1
target=$2

if [[ $# == 1 ]]; then
  git clone "$repo"
elif [[ -e "$target" ]]; then
  echo "Target $target exists. Skip cloning $repo." >&2
else
  git clone "$repo" "$target"
fi
