#!/bin/bash

if [ $# -ne 2 ]; then
  echo Usage: make-symlink source target > /dev/stderr
  exit 1
fi

src=$1
target=$2

if [ -e "$target" ]; then
  echo "Target $target exists. Skip creating symlink of $src." > /dev/stderr
else
  ln -s "$src" "$target"
fi
