#!/bin/bash
set -euo pipefail

readonly CMDNAME="${BASH_SOURCE[0]##*/}"

if [[ $# -ne 2 ]]; then
  echo "Usage: $CMDNAME source target" >&2
  exit 1
fi

src=$1
target=$2

if [[ -e "$target" ]]; then
  echo "Target $target exists. Skipping creating symlink of $src." >&2
else
  mkdir -p "${target%/*}"
  ln -s "$src" "$target"
fi
