name: CI

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  test:
    name: Test
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test setup scripts
      run: ./setup
    - name: Run shellcheck
      run: ./script/ci
